version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis  # Correct format: "KEY=VALUE"
      - ANOTHER_VAR=some_value
      - DEBUG=true

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"